import { DefaultTheme } from 'styled-components';

export const lightTheme = {
	scheme: 'light',
	positive1: '#64B686',
	positive2: '#4EA673',
	caution1: '#EECA00',
	negative1: '#F16A82',
	negative2: '#EE4463',
	neutral1: '#f5f5f5',
	neutral2: '#F0F0F0',
	neutral3: '#E9E9E9',
	neutral4: '#D9D9D9',
	neutral5: '#A8A8A8',
	neutral6: '#909090',
	neutral7: '#787878',
	neutral8: '#565656',
	neutral9: '#333333',
	neutralA1: '#444444',
	neutralA2: '#2A2A2A',
	neutralA3: '#404040',
	neutralA4: '#505050',
	neutralA5: '#181818',
	neutralA6: '#A0A0A0',
	neutralA7: '#BEBEBE',
	overlay1: 'rgb(0, 0, 0, .45)',
	overlay2: 'rgb(0, 0, 0, .5)',
	shadow1: 'rgb(220, 220, 220, .5)',
	primary1: '#000000',
	primary2: '#333333',
	light1: '#FFFFFF',
	light2: '#F2F2F2',
	light3: '#B0B0B0',
	dark1: '#121212',
	dark2: '#2A2A2A',
	link1: '#0074E4',
	link2: '#009AF7',
	editor: {
		primary: '#ec3063',
		alt1: '#13ab8f',
		alt2: '#5E66DB',
		alt3: '#00a66b',
		alt4: '#006dff',
		alt5: '#8580d9',
		alt6: '#FF5722',
		alt7: '#FFC107',
		alt8: '#1681c7',
		alt9: '#8BC34A',
		alt10: '#3a3a3a',
	},
	actions: {
		eval: '#b86ac2',
		info: '#b86ac2',
		balance: '#b86ac2',
		transfer: '#eb9330',
		creditNotice: '#51af88',
		debitNotice: '#d43b7a',
		none: '#474747',
		other: '#6086e3',
	},
};

export const darkTheme = {
	scheme: 'dark',
	positive1: '#38BD80',
	positive2: '#2F9D6A',
	caution1: '#EECA00',
	negative1: '#F16A82',
	negative2: '#EE4463',
	neutral1: '#171717',
	neutral2: '#1D1D1D',
	neutral3: '#2E2E2E',
	neutral4: '#383838',
	neutral5: '#444444',
	neutral6: '#606060',
	neutral7: '#5E5E5E',
	neutral8: '#6C6C6C',
	neutral9: '#7A7A7A',
	neutralA1: '#F2F2F2',
	neutralA2: '#E0E0E0',
	neutralA3: '#CECECE',
	neutralA4: '#BCBCBC',
	neutralA5: '#D9D9D9',
	neutralA6: '#979797',
	neutralA7: '#7F7F7F',
	overlay1: 'rgba(0, 0, 0, 0.45)',
	overlay2: 'rgba(0, 0, 0, 0.65)',
	shadow1: 'rgba(0, 0, 0, 0.4)',
	primary1: '#666666',
	primary2: '#888888',
	light1: '#FFFFFF',
	light2: '#EAEAEA',
	light3: '#C2C2C2',
	dark1: '#0C0C0C',
	dark2: '#1A1A1A',
	link1: '#009AF7',
	link2: '#0074E4',
	editor: {
		primary: '#DA615D',
		alt1: '#62c1b1',
		alt2: '#6AB586',
		alt3: '#5bdcbf',
		alt4: '#616ACC',
		alt5: '#6EB9CB',
		alt6: '#FF5722',
		alt7: '#6AB586',
		alt8: '#00BCD4',
		alt9: '#8BC34A',
		alt10: '#bcbcbc',
	},
	actions: {
		eval: '#b86ac2',
		info: '#b86ac2',
		balance: '#b86ac2',
		transfer: '#eb9330',
		creditNotice: '#51af88',
		debitNotice: '#d43b7a',
		none: '#474747',
		other: '#6086e3',
	},
};

export const theme = (currentTheme: any): DefaultTheme => ({
	scheme: currentTheme.scheme,
	colors: {
		accordion: {
			background: currentTheme.neutral1,
			hover: currentTheme.neutral2,
			color: currentTheme.neutralA1,
		},
		actions: {
			eval: currentTheme.actions.eval,
			info: currentTheme.actions.info,
			balance: currentTheme.actions.balance,
			transfer: currentTheme.actions.transfer,
			debitNotice: currentTheme.actions.debitNotice,
			creditNotice: currentTheme.actions.creditNotice,
			none: currentTheme.actions.none,
			other: currentTheme.actions.other,
		},
		border: {
			primary: currentTheme.neutral4,
			alt1: currentTheme.neutral3,
			alt2: currentTheme.neutral7,
			alt3: currentTheme.neutral8,
			alt4: currentTheme.neutralA5,
			alt5: currentTheme.primary1,
			alt6: currentTheme.primary2,
		},
		button: {
			primary: {
				background: currentTheme.neutral1,
				border: currentTheme.neutral5,
				color: currentTheme.neutralA1,
				active: {
					background: currentTheme.neutral4,
					border: currentTheme.neutralA6,
					color: currentTheme.neutralA1,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral5,
					color: currentTheme.neutral7,
				},
			},
			alt1: {
				background: currentTheme.neutral3,
				border: currentTheme.neutral5,
				color: currentTheme.neutralA1,
				active: {
					background: currentTheme.primary1,
					border: currentTheme.primary1,
					color: currentTheme.light1,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral5,
					color: currentTheme.neutral7,
				},
			},
			alt2: {
				background: currentTheme.neutralA1,
				border: currentTheme.neutralA1,
				color: currentTheme.neutralA1,
				active: {
					background: currentTheme.neutralA4,
					border: currentTheme.neutralA4,
					color: currentTheme.neutralA4,
				},
				disabled: {
					background: currentTheme.neutral3,
					border: currentTheme.neutral3,
					color: currentTheme.neutral7,
				},
			},
		},
		checkbox: {
			active: {
				background: currentTheme.primary1,
			},
			background: currentTheme.neutral1,
			hover: currentTheme.neutral3,
			disabled: currentTheme.neutral5,
		},
		container: {
			primary: {
				background: currentTheme.neutral1,
				active: currentTheme.neutral3,
			},
			alt1: {
				background: currentTheme.neutral2,
			},
			alt2: {
				background: currentTheme.neutral3,
			},
			alt3: {
				background: currentTheme.neutral4,
			},
			alt4: {
				background: currentTheme.neutral5,
			},
			alt5: {
				background: currentTheme.neutralA4,
			},
			alt6: {
				background: currentTheme.primary1,
			},
			alt7: {
				background: currentTheme.neutralA3,
			},
			alt8: {
				background: currentTheme.dark2,
			},
			alt9: {
				background: currentTheme.primary1,
			},
			alt10: {
				background: currentTheme.primary2,
			},
		},
		contrast: {
			background: currentTheme.dark2,
			border: currentTheme.neutral9,
			color: currentTheme.light1,
		},
		font: {
			primary: currentTheme.neutralA1,
			alt1: currentTheme.neutralA5,
			alt2: currentTheme.neutralA3,
			alt3: currentTheme.neutral8,
			alt4: currentTheme.neutral1,
			alt5: currentTheme.primary1,
			light1: currentTheme.light1,
			light2: currentTheme.light2,
			light3: currentTheme.light3,
			dark1: currentTheme.dark1,
			dark2: currentTheme.dark2,
		},
		form: {
			background: currentTheme.neutral1,
			border: currentTheme.neutral5,
			invalid: {
				outline: currentTheme.negative1,
				shadow: currentTheme.negative2,
			},
			valid: {
				outline: currentTheme.neutralA5,
				shadow: currentTheme.neutralA6,
			},
			default: {
				outline: currentTheme.neutralA5,
				shadow: currentTheme.neutralA6,
			},
			disabled: {
				background: currentTheme.neutral2,
				border: currentTheme.neutral5,
				label: currentTheme.neutralA2,
			},
		},
		gradient: {
			start: currentTheme.primary1,
			middle: currentTheme.primary1,
			end: currentTheme.primary2,
		},
		icon: {
			primary: {
				fill: currentTheme.neutralA4,
				active: currentTheme.neutral3,
				disabled: currentTheme.neutralA3,
			},
			alt1: {
				fill: currentTheme.neutral4,
				active: currentTheme.neutral5,
				disabled: currentTheme.neutral3,
			},
			alt2: {
				fill: currentTheme.neutralA1,
				active: currentTheme.neutralA4,
				disabled: currentTheme.neutral3,
			},
			alt3: {
				fill: currentTheme.neutralA2,
				active: currentTheme.neutral1,
				disabled: currentTheme.neutral3,
			},
		},
		indicator: {
			active: currentTheme.positive1,
		},
		link: {
			color: currentTheme.link1,
			active: currentTheme.link2,
		},
		loader: {
			primary: currentTheme.primary1,
		},
		overlay: {
			primary: currentTheme.overlay1,
			alt1: currentTheme.overlay2,
		},
		editor: {
			primary: currentTheme.editor.primary,
			alt1: currentTheme.editor.alt1,
			alt2: currentTheme.editor.alt2,
			alt3: currentTheme.editor.alt3,
			alt4: currentTheme.editor.alt4,
			alt5: currentTheme.editor.alt5,
			alt6: currentTheme.editor.alt6,
			alt7: currentTheme.editor.alt7,
			alt8: currentTheme.editor.alt8,
			alt9: currentTheme.editor.alt9,
			alt10: currentTheme.editor.alt10,
		},
		row: {
			active: {
				background: currentTheme.neutral3,
				border: currentTheme.neutral2,
			},
			hover: {
				background: currentTheme.neutral2,
			},
		},
		scrollbar: {
			track: currentTheme.neutral2,
			thumb: currentTheme.neutral5,
		},
		shadow: {
			primary: currentTheme.shadow1,
		},
		status: {
			draft: currentTheme.caution1,
			published: currentTheme.positive1,
		},
		tabs: {
			color: currentTheme.neutralA4,
			active: {
				background: currentTheme.primary1,
				color: currentTheme.neutralA1,
			},
		},
		view: {
			background: currentTheme.neutral1,
		},
		warning: {
			primary: currentTheme.negative1,
			alt1: currentTheme.negative2,
		},
	},
	typography: {
		family: {
			primary: `'DM Sans', sans-serif`,
			alt1: `'Geist Mono', monospace`,
			alt2: `'Geist Mono', monospace`,
		},
		size: {
			xxxSmall: '11px',
			xxSmall: '13px',
			xSmall: '14px',
			small: '15px',
			base: '16px',
			lg: '18px',
			xLg: '24px',
			xxLg: '28px',
			h1: 'clamp(36px, 3.5vw, 56px)',
			h2: 'clamp(32px, 3.25vw, 50px)',
			h4: 'clamp(28px, 2.5vw, 32px)',
		},
		weight: {
			light: '300',
			regular: '400',
			medium: '500',
			bold: '600',
			xBold: '700',
		},
	},
});
